# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eece054733dafad84c40103f7138cd35d176ac914a876270930691e0b1e6ae4a0836b4130f4e7fdc8914e8827d2db4d53f593f51e3cf763d0311c97834f7fbb1

test:
  secret_key_base: 49997cf68fae03a1cfa986696b3c0e627b00d2921c2232c76e292b26ed8cf1cb75031793ae9b7563711b6aa10cdd425c73a55f77deb58dc1c65ad7fc5d5c60b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
